name: Build Information

on:
  push:

env:
  APP_NAME: ShoppingApp
  VERSION: v1.0.0

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Print Build Information

        run: |
          echo "Application : $APP_NAME"
          echo "Version     : $VERSION"
          echo "Developer   : ${{ github.actor }}"
          echo "Repository  : ${{ github.repository }}"
          echo "Branch      : ${{ github.ref_name }}"
          echo "Workflow    : ${{ github.workflow }}"
          echo "OS          : ${{ runner.os }}"
          echo "Commit      : ${{ github.sha }}"
