name: varibales

on: 
  push:

jobs:
  variable-demo:
     runs-on: ubuntu-latest
     env:
       NAME= brahma
       CITY= hyderabad
       JOB= devops
     steps: 
     - name: print varibales
       run: |
       echo "NAME = $NAME"
       echo "CITY = $CITY"
       echo "JOB = $JOB"
